import Footer from "@/components/global/footer/Footer";
import Navbar from "@/components/global/navbar/Navbar";
import BackToTop from "@/components/ui/back-to-top";
import { routing } from "@/i18n/routing";
import { MainRoutesParams } from "@/lib/types";
import Providers from "@/providers/Providers";
import { gilroy } from "@/public/fonts";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";
import "../globals.css";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: MainRoutesParams;
}>) {
  const { locale } = await params;

  setRequestLocale(locale);

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body className={`${gilroy.variable} antialiased`}>
        <Providers
          locale={locale}
          messages={messages}
          attribute="class"
          defaultTheme="light"
        >
          <div className="absolute top-0 right-0 left-0 z-50 bg-transparent">
            <Navbar />
          </div>
          <main className="selection:bg-primary min-h-screen">{children}</main>
          <Footer />
          <BackToTop />
          <Toaster closeButton richColors position="bottom-center" />
        </Providers>
      </body>
    </html>
  );
}
